# Site settings
title: Noted
email: chrisbarnettster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes on ideas, experiments, and early concepts.
github_username:  chrisbarnettster
theme: minima
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
plugins:
  - jekyll-last-modified-at
