# Site settings
title: arxiv posts
email: chrisbarnettster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Drafting some posts in blog format. arxiv, pre-release concept.
github_username:  chrisbarnettster
theme: minima
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
